version: '3.5'

services:
  db:
    container_name: database
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5436:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local